begin;

drop table if exists kershaw.pitches;

create table kershaw.pitches (
	pitch_type		text,
	game_date		text,
	release_speed		text,
	release_pos_x		text,
	release_pos_z		text,
	player_name		text,
	batter			text,
	pitcher			text,
	events			text,
	description		text,
	spin_dir		text,
	spin_rate_deprecated	text,
	break_angle_deprecated	text,
	break_length_deprecated	text,
	zone			text,
	des			text,
	game_type		text,
	stand			text,
	p_throws		text,
	home_team		text,
	away_team		text,
	type			text,
	hit_location		text,
	bb_type			text,
	balls			text,
	strikes			text,
	game_year		text,
	pfx_x			text,
	pfx_z			text,
	plate_x			text,
	plate_z			text,
	on_3b			text,
	on_2b			text,
	on_1b			text,
	outs_when_up		text,
	inning			text,
	inning_topbot		text,
	hc_x			text,
	hc_y			text,
	tfs_deprecated		text,
	tfs_zulu_deprecated	text,
	fielder_2		text,
	umpire			text,
	sv_id			text,
	vx0			text,
	vy0			text,
	vz0			text,
	ax			text,
	ay			text,
	az			text,
	sz_top			text,
	sz_bot			text,
	hit_distance_sc		text,
	launch_speed		text,
	launch_angle		text,
	effective_speed		text,
	release_spin_rate	text,
	release_extension	text,
	game_pk			text,
	pitcher2		text,
	fielder_2b		text,
	fielder_3		text,
	fielder_4		text,
	fielder_5		text,
	fielder_6		text,
	fielder_7		text,
	fielder_8		text,
	fielder_9		text,
	release_pos_y		text,
	estimated_ba_using_speedangle	text,
	estimated_woba_using_speedangle	text,
	woba_value			text,
	woba_denom			text,
	babip_value			text,
	iso_value			text,
	launch_speed_angle		text,
	at_bat_number			text,
	pitch_number			text,
	pitch_name			text,
	home_score			text,
	away_score			text,
	bat_score			text,
	fld_score			text,
	post_away_score			text,
	post_home_score			text,
	post_bat_score			text,
	post_fld_score			text,
	if_fielding_alignment		text,
	of_fielding_alignment		text
--	primary key (match_id)
);

copy kershaw.pitches from '/tmp/kershaw.csv' with delimiter as ',' csv header quote as '"';

commit;
